authenticate.code:
    path:      /code
    defaults:
        _controller: UserBundle:Authenticate:code
    methods: [POST]
#    requirements:
#        code: '\s+'

authenticate.authorize:
    path:      /authorize
    defaults:
        _controller: UserBundle:Authenticate:authorize
        _format: json
    methods: [GET]


authenticate.user_details:
    path:      /api/access-token/{accessToken}/refresh-token/{refreshToken}/user-details
    defaults:
        _controller: UserBundle:Authenticate:userDetail
        _format: json
    methods: [POST]
#    requirements:
#        refreshToken: '\s+'
#        accessToken: '\d+'