authenticate.code:
    path:      /code
    defaults:
        _controller: UserBundle:Authenticate:code
    methods: [POST]

authenticate.authorize:
    path:      /authorize
    defaults:
        _controller: UserBundle:Authenticate:authorize
        _format: json
    methods: [GET]

authenticate.user_details:
    path: /access-token/{accessToken}/refresh-token/{refreshToken}/user-details
    defaults:
        _controller: UserBundle:Authenticate:userDetail
        _format: json
    methods: [POST]
