get.events:
    path:      /events.{_format}
    defaults: {
        _controller: EventManagementBundle:Event:getEvents,
        _format: json
        }
    methods: [GET]

create.event:
    path:      /event.{_format}
    defaults: {
        _controller: EventManagementBundle:Event:createEvent,
        _format: json
        }
    methods: [POST]
