##############################
#           EVENT            #
##############################
event.get_collection:
    path:      /events
    defaults:
        _controller: EventManagementBundle:Event:collection
        _format: json
        limit: 10
        page: 10
    methods: [GET]
    requirements:
        limit: '\d+'
        page: '\d+'

event.get_single:
    path:       /event/{eventId}
    defaults:
        _controller: EventManagementBundle:Event:single
        _format: json
    methods: [GET]

event.create:
    path:      /event
    defaults:
        _controller: EventManagementBundle:Event:create
        _format: json
    methods: [POST]

event.edit:
    path:      /event/{eventId}
    defaults:
        _controller: EventManagementBundle:Event:edit
        _format: json
    methods: [PUT]

event.delete:
    path:      /event/{eventId}
    defaults:
        _controller: EventManagementBundle:Event:delete
        _format: json
    methods: [DELETE]

event.single_enable:
    path:      /event/enable/{eventId}
    defaults:
        _controller: EventManagementBundle:Event:enable
        _format: json
    methods: [PUT]

event.single_disable:
    path:       /event/disable/{eventId}
    defaults:
        _controller: EventManagementBundle:Event:disable
        _format: json
    methods: [PUT]

##############################
#           Tag              #
##############################

tag.get_collection:
    path:      /event/{eventId}/tags
    defaults:
        _controller: EventManagementBundle:Tag:collection
        _format: json
    methods: [GET]
    requirements:
        limit: '\d+'
        page: '\d+'

tag.get_single:
    path:       /tag/{tagId}
    defaults:
        _controller: EventManagementBundle:Tag:single
        _format: json
    methods: [GET]

tag.create:
    path:      /tag
    defaults:
        _controller: EventManagementBundle:Tag:create
        _format: json
    methods: [POST]

tag.edit:
    path:      /tag/{tagId}
    defaults:
        _controller: EventManagementBundle:Tag:edit
        _format: json
    methods: [PUT]

tag.delete:
    path:      /tag/{tagId}
    defaults:
        _controller: EventManagementBundle:Tag:delete
        _format: json
    methods: [DELETE]

tag.single_enable:
    path:      /tag/enable/{tagId}
    defaults:
        _controller: EventManagementBundle:Tag:enable
        _format: json
    methods: [PUT]

tag.single_disable:
    path:       /tag/disable/{tagId}
    defaults:
        _controller: EventManagementBundle:Tag:disable
        _format: json
    methods: [PUT]


##############################
#           Guest            #
##############################

guest.get_collection:
    path:      /event/{eventId}/guests
    defaults:
        _controller: EventManagementBundle:Guest:collection
        _format: json
    methods: [GET]
    requirements:
        eventId: '\d+'
        limit: '\d+'
        page: '\d+'

guest.get_collection_special_tag:
    path:      /event/{eventId}/tag/{tagId}/guests
    defaults:
        _controller: EventManagementBundle:Guest:collectionByTag
        _format: json
    methods: [GET]
    requirements:
        eventId: '\d+'
        tagId: '\d+'
        limit: '\d+'
        page: '\d+'

guest.get_single:
    path:       /guest/{guestId}
    defaults:
        _controller: EventManagementBundle:Guest:single
        _format: json
    methods: [GET]

guest.create:
    path:      /guest
    defaults:
        _controller: EventManagementBundle:Guest:create
        _format: json
    methods: [POST]

guest.edit:
    path:      /guest/{guestId}
    defaults:
        _controller: EventManagementBundle:Guest:edit
        _format: json
    methods: [PUT]

guest.delete:
    path:      /guest/{guestId}
    defaults:
        _controller: EventManagementBundle:Guest:delete
        _format: json
    methods: [DELETE]

guest.single_enable:
    path:      /guest/enable/{guestId}
    defaults:
        _controller: EventManagementBundle:Guest:enable
        _format: json
    methods: [PUT]

guest.single_disable:
    path:       /guest/disable/{guestId}
    defaults:
        _controller: EventManagementBundle:Guest:disable
        _format: json
    methods: [PUT]