EventManagementBundle\Entity\Event:
    properties:
        description:
            - NotBlank: { message: Opis nie może być pusty }
            - Type: string

        name:
            - NotBlank: { message: Nazwa nie może być puste }
            - Type: string

        eventTerm:
            - NotBlank: { message: Data wydarzenia nie może być pusta }
            - Type: datetime