EventManagementBundle\Entity\Event:
    properties:
        description:
            - NotBlank: ~
            - Type: string

        name:
            - NotBlank: ~
            - Type: string

        eventTerm:
            - NotBlank:
            - Type: datetime