security:
   encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

   providers:
      fos_userbundle:
          id: fos_user.user_provider.username_email

   firewalls:
      oauth_token:
          pattern:    ^/oauth/v2/token
          security:   false

      api_doc:
          pattern:    ^/api/doc
          anonymous: true

      api_resources:
          pattern:    ^/api
          fos_oauth:  true
          stateless:  true
          anonymous: false

      secure_area:
         pattern:    ^/
         fos_oauth: true
         form_login:
            provider: fos_userbundle
            login_path: fos_user_security_login
            check_path: fos_user_security_check
         logout:
            handlers: [logout_listener]
            path:   /logout
            target: /login
         anonymous: ~

   access_control:
      - { path: ^/api/doc, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/api, roles: ROLE_USER }


