EventManagementBundle\Representation\EventRepresentation:
    exclusion_policy: ALL
    properties:
        id:
            type: int
            expose: true

        name:
            type: string
            expose: true

        createdAt:
            expose: true
            type: DateTime<'Y-m-d'>

        eventTerm:
            expose: true
            type: DateTime<'Y-m-d'>

        description:
            type: string
            expose: true

        active:
            type: boolean
            expose: true
