services:
    api.scope_annotation_reader:
        class: ApiBundle\Annotation\ScopeAnnotationReader
        tags:
            - { name: kernel.event_subscriber }
        arguments:
            - '@annotation_reader'
            - '@api.allowed_scopes_repository'
            - '@api.transformer_scope_repository'

    api.scope_listener:
        class: ApiBundle\Annotation\ScopeListener
        tags:
            - { name: kernel.event_subscriber }
        arguments:
            - '@api.transformer_scope_repository'

    api.nelmio_api_doc.scope_handler:
        class: ApiBundle\Documentation\ScopeAnnotationHandler
        tags:
            - { name: nelmio_api_doc.extractor.handler }
