services:
    api.main_transformer:
        class: ApiBundle\Transformer\Transformer

    abstract.transformer:
        class: ApiBundle\Transformer\AbstractTransformer
        abstract: true
        arguments:
            - '@api.transformer_scope_repository'
        calls:
            - [setTransformer, ['@api.main_transformer']]

    api.transformer_scope_repository:
        class: ApiBundle\Transformer\Scope\ScopeRepository

    api.allowed_scopes_repository:
        class: ApiBundle\Transformer\Scope\AllowedScopesRepository

    api.abstract_transformer_scope:
        class: ApiBundle\Transformer\Scope\AbstractTransformerScope
        abstract: true
        arguments:
            - '@doctrine.orm.entity_manager'
        calls:
            - [setTransformer, ['@api.main_transformer']]

    api.scope_annotation_reader:
        class: ApiBundle\Annotation\ScopeAnnotationReader
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
        arguments:
            - '@annotation_reader'
            - '@api.allowed_scopes_repository'
            - '@api.transformer_scope_repository'