services:
    api.main_transformer:
        class: ApiBundle\Transformer\Transformer

    abstract.transformer:
        class: ApiBundle\Transformer\AbstractTransformer
        abstract: true
        arguments: ['@api.main_transformer']