services:
    api.main_transformer:
        class: ApiBundle\Transformer\Transformer

    abstract.transformer:
        class: ApiBundle\Transformer\AbstractTransformer
        abstract: true
        arguments:
            - '@api.main_transformer'

    api.transformer_scope_repository:
        class: ApiBundle\Transformer\Scope\ScopeRepository

    api.allowed_scopes_repository:
        class: ApiBundle\Transformer\Scope\AllowedScopesRepository
        parent: api.transformer_scope_repository

    api.transformer_scope:
        class: ApiBundle\Transformer\Scope\TransformerScope
        arguments:
            - '@api.transformer_scope_repository'

    api.abstract_transformer_scope:
        class: ApiBundle\Transformer\Scope\AbstractTransformerScope
        abstract: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@api.main_transformer'
            - '@api.allowed_scopes_repository'

