services:
    #Transformer
    api.main_transformer:
        class: ApiBundle\Transformer\Transformer
        arguments:
            - '@api.transformer_scope_repository'

    abstract.transformer:
        class: ApiBundle\Transformer\AbstractTransformer
        abstract: true
        calls:
            - [setTransformer, ['@api.main_transformer']]

    api.transformer_scope_repository:
        class: ApiBundle\Transformer\Scope\ScopeRepository

    api.allowed_scopes_repository:
        class: ApiBundle\Transformer\Scope\AllowedScopesRepository

    api.abstract_transformer_scope:
        class: ApiBundle\Transformer\Scope\AbstractTransformerScope
        abstract: true
        arguments:
            - '@doctrine.orm.entity_manager'
        calls:
            - [setTransformer, ['@api.main_transformer']]

    #Voter
    api.abstract_voter:
        class: ApiBundle\Security\Voter\AbstractVoter
        abstract: true
        public: false
        arguments:
            - '@security.access.decision_manager'
            - '@doctrine.orm.entity_manager'


