services:
    api.main_transformer:
        class: ApiBundle\Transformer\Transformer
        arguments:
            - '@api.transformer_scope_repository'

    abstract.transformer:
        class: ApiBundle\Transformer\AbstractTransformer
        abstract: true
        calls:
            - [setTransformer, ['@api.main_transformer']]

    api.transformer_scope_repository:
        class: ApiBundle\Transformer\Scope\ScopeRepository

    api.allowed_scopes_repository:
        class: ApiBundle\Transformer\Scope\AllowedScopesRepository

    api.abstract_transformer_scope:
        class: ApiBundle\Transformer\Scope\AbstractTransformerScope
        abstract: true
        arguments:
            - '@doctrine.orm.entity_manager'
        calls:
            - [setTransformer, ['@api.main_transformer']]

    api.scope_annotation_reader:
        class: ApiBundle\Annotation\ScopeAnnotationReader
        tags:
            - { name: kernel.event_subscriber }
        arguments:
            - '@annotation_reader'
            - '@api.allowed_scopes_repository'
            - '@api.transformer_scope_repository'

    api.scope_listener:
        class: ApiBundle\Annotation\ScopeListener
        tags:
            - { name: kernel.event_subscriber }
        arguments:
            - '@api.transformer_scope_repository'

    api.nelmio_api_doc.scope_handler:
        class: ApiBundle\Documentation\ScopeAnnotationHandler
        tags:
            - { name: nelmio_api_doc.extractor.handler }