services:
    guzzle.client:
        class: GuzzleHttp\Client

    authorization_code_model:
        class: UserBundle\Model\AuthorizationCodeModel

    generate_access_token:
        class: UserBundle\Security\GenerateAccessToken
        arguments:
            - '@authorization_code_model'
            - '@guzzle.client'

    code_resolver:
        class: UserBundle\Resolver\CodeResolver
        arguments: ['@authorization_code_model']

    confirmation_window.disable:
        class: UserBundle\Subscriber\ConfirmationWindow
        tags:
          - { name: kernel.event_listener, event: fos_oauth_server.pre_authorization_process, method: onPreAuthorizationProcess }

    logout_listener:
          class: UserBundle\Subscriber\LogoutListener
          arguments:
              - "@fos_user.user_manager"