services:
    repository.event:
        class: Doctrine\ORM\EntityRepository
        factory:
            - '@doctrine.orm.default_entity_manager'
            - getRepository
        arguments:
            - 'EventManagementBundle:Event'
        tags:
            - { name: api.sort_and_filtered_repository }

    repository.guest:
        class: Doctrine\ORM\EntityRepository
        factory:
            - '@doctrine.orm.default_entity_manager'
            - getRepository
        arguments:
            - 'EventManagementBundle:Guest'
        tags:
            - { name: api.sort_and_filtered_repository }

    repository.tag:
        class: Doctrine\ORM\EntityRepository
        factory:
            - '@doctrine.orm.default_entity_manager'
            - getRepository
        arguments:
            - 'EventManagementBundle:Tag'
        tags:
            - { name: api.sort_and_filtered_repository }
