services:
    repository.event: &DEFULT_REPOSITORY
        class: Doctrine\ORM\EntityRepository
        factory:
            - '@doctrine.orm.default_entity_manager'
            - getRepository
        arguments:
            - 'EventManagementBundle:Event'
        tags:
            - { name: api.sort_and_filtered_repository }

    repository.guest:
        <<: *DEFULT_REPOSITORY
        class: Doctrine\ORM\EntityRepository
        arguments:
            - 'EventManagementBundle:Guest'

    repository.tag:
        <<: *DEFULT_REPOSITORY
        class: Doctrine\ORM\EntityRepository
        arguments:
            - 'EventManagementBundle:Tag'
