services:
    event_management_event_transformer_scope.guest_tag_scope: &DEFAULT_SCOPE
        class: EventManagementBundle\Transformer\Scope\GuestTagScope
        parent: 'api.abstract_transformer_scope'
        tags:
            - { name: api.transformer_scope }

    event_management_event_transformer_scope.user_scope:
        class: EventManagementBundle\Transformer\Scope\UserScope
        <<: *DEFAULT_SCOPE