services:
    guest.tag_transformer_scope:
        class: EventManagementBundle\Transformer\Scope\GuestTagScope
        parent: 'api.abstract_transformer_scope'
        tags:
            - { name: api.transformer_scope }

    event.user_transformer_scope:
        class: EventManagementBundle\Transformer\Scope\UserScope
        parent: 'api.abstract_transformer_scope'
        tags:
            - { name: api.transformer_scope }
