services:
    event.transformer:
        class: EventManagementBundle\Transformer\EventTransformer
        tags:
            - { name: api.transformer }

    event.colelction.transformer:
        class: EventManagementBundle\Transformer\Collection\EventCollectionTransformer
        parent: 'abstract.transformer'
        tags:
            - { name: api.transformer }

    event.user_transformer_scope:
        class: EventManagementBundle\Transformer\Scope\UserScope
        parent: 'api.abstract_transformer_scope'
        tags:
            - { name: api.transformer_scope }

    event.access_voter:
        class: EventManagementBundle\Security\Voters\EventAccessVoter
        parent: 'api.abstract_voter'
        tags:
            - { name: security.voter }