services:
    event_management_event_transformer.tag_transformer: &DEFAULT_TRANSFORMER
        class: EventManagementBundle\Transformer\TagTransformer
        tags:
            - { name: api.transformer }

    event_management_event_transformer.guest_transformer:
        class: EventManagementBundle\Transformer\GuestTransformer
        <<: *DEFAULT_TRANSFORMER

    event_management_event_transformer.event_transformer:
        class: EventManagementBundle\Transformer\EventTransformer
        <<: *DEFAULT_TRANSFORMER


#    COLLECTIONS TRANSFORMERS
    event_management_event_transformer_collection.event_collection_transformer: &DEFAULT_COLLECTION_TRANSFORMER
        class: EventManagementBundle\Transformer\Collection\EventCollectionTransformer
        parent: 'abstract.transformer'
        tags:
            - { name: api.transformer }

    event_management_event_transformer_collection.tag_collection_transformer:
        class: EventManagementBundle\Transformer\Collection\TagCollectionTransformer
        <<: *DEFAULT_COLLECTION_TRANSFORMER

    event_management_event_transformer_collection.guest_collection_transformer:
        class: EventManagementBundle\Transformer\Collection\GuestCollectionTransformer
        <<: *DEFAULT_COLLECTION_TRANSFORMER