ApiBundle\Representation\ExampleRepresentation:
    exclusion_policy: ALL
    properties:
        id:
            type: int
            expose: true
        name:
            type: string
            expose: true
